/*
 *   █████╗ ██╗   ██╗     ██████╗ ███████╗ ██████╗
 *  ██╔══██╗╚██╗ ██╔╝     ██╔══██╗██╔════╝██╔════╝
 *  ███████║ ╚████╔╝█████╗██████╔╝███████╗██║  ███╗
 *  ██╔══██║  ╚██╔╝ ╚════╝██╔═══╝ ╚════██║██║   ██║
 *  ██║  ██║   ██║        ██║     ███████║╚██████╔╝
 *  ╚═╝  ╚═╝   ╚═╝        ╚═╝     ╚══════╝ ╚═════╝
 *    (c) doublezerowld 2026, MIT or Apache-2.0
*/
//! # A platform-agnostic, no_std generic driver for the AY-3-8910 family of 3‑voice PSG sound chips.
//!
//! This crate contains functions for interacting with emulated or physical AY-3-8910 chips.
//! It provides a CommandOutput trait that allows the end user to define how register-value pairs
//! generated by the code are handled.
//!
//! # Features
//! **notes** - Basic musical note support
//!
//! **read** - I/O read operation support
//!
//! # Compatibility
//! This code should be backwards-compatible with other PSG sound chips based on the AY-3-8910, such as the YM2149, AY-3-8910 and Sunsoft 5B.
//!
//! ***When in doubt, check the datasheet!***

// lib.rs is just some glue code... go check out the other files, they're much more interesting!
#![no_std]
pub mod audio;
pub mod chip;
pub mod command;
pub mod errors;
pub mod io;
pub mod notes;
pub mod prelude {
    pub use crate::{
        chip::PSG,
        command::{Command, CommandOutput},
    };
}
pub mod register;
